version: '3'

services:
  app:
    build: .
    user: root
    image: opillinois-api-app
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - .:/usr/src/oneplace-illinois-api
    ports:
      - '80:80'
    networks:
      - default
    env_file:
      - .env.docker # postgres env data & app's PORT
    environment:
      POSTGRES_HOST: postgres
    command: sh -c "
        NODE_ENV=test node src/workers/parse-course-csv.js
        && npm ci
        && npm start
      "

  postgres:
    image: postgres:13.3-alpine
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data # persistent data
    ports:
      - "5435:5432" # unusual port 5435!
    networks:
      - default
    env_file:
      - .env.docker # set up postgres (see .env.docker.example)

volumes:
  db-data: